spring.application.name=Sanitario



spring.datasource.url=jdbc:postgresql://ep-gentle-sky-aq9fm974-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_fKXW0ruOFEn6


# Configuraci\u00f3n de Hibernate
#update: hara la actualizacion entre lo que dice spring y BD
#create-drop: borra todo lo anterior y lo vuelve a crear
#validate:
#none: solo te estas conectando
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pool de conexiones (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
